server:
  port: ${PORT:8080}

spring:
  application:
    name: shoe-moa
  profiles:
    active: prod   # 기본 실행 프로파일
  output:
    ansi:
      enabled: always
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
#        use_sql_comments: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${GMAIL_USERNAME:}
    password: ${GMAIL_APP_PASSWORD:}
    protocol: smtp
    default-encoding: UTF-8

    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connection-timeout: 5000
          timeout: 5000
          write-timeout: 5000


logging:
  level:
#    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace

springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true

  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    tags-sorter: alpha
    operations-sorter: alpha
    display-request-duration: true   # 요청 시간 표시
    doc-expansion: none              # 기본 접힘 상태 (none, list, full)
    default-models-expand-depth: -1  # 하단 schema 숨김 (깔끔해짐)

  override-with-generic-response: false
  show-actuator: false


jwt:
  secret: ${JWT_SECRET}
  expiration: 3600000  # 1시간 (밀리초 단위)
  refresh-expiration: 604800000


app:
  base-url: ${APP_BASE_URL:http://localhost:3000}
  admin:
    initial-password: ${ADMIN_PW}
  cors:
    allowed-origins: ${APP_CORS_ALLOWED_ORIGINS:http://localhost:3000}
